version: "2"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: yarn start
    ports:
    - 3000:3000
    environment:
      - MapboxAccessToken=${MapboxAccessToken}
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src

  prod:
    build: .
    ports:
    - 80:80
    environment:
      - MapboxAccessToken=${MapboxAccessToken}
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./build:/usr/src/app/build
