FROM node:8-alpine as build

WORKDIR /usr/src/app
COPY package.json /usr/src/app
RUN yarn install

COPY ./public /usr/src/app/public
COPY ./src /usr/src/app/src
RUN yarn build

EXPOSE 3000
CMD ["yarn", "start"]
