version: "2"

services:
  app:
    build: .
    environment:
      - MapboxAccessToken=${MapboxAccessToken}
    command: yarn start
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src

    # command: yarn build
    # volumes:
    #   - ./public:/usr/src/app/public
    #   - ./src:/usr/src/app/src
    #   - ./build:/usr/src/app/build
